### ISSUE TITLE
Question regarding Nextcloud on K8s

### ISSUE THREAD

**Issue by diraol** [alexblackie/watashi#1]
Hi Alex!

First of all, thanks for sharing [your experience](https://www.alexblackie.com/articles/nextcloud-on-k8s/) with Nextcloud @ K8s! It is a very nice write up!

I have a question though.
How are you dealing with Nextcloud database? Are you using any SQL Database as a Service (RDS or similar)?

Another question is that your Prision docker image is using a `AZURE_STORAGE_WEBROOT_URL` variable. But in your post you are using Minio as a proxy to S3. So, what is the "final" architecture here?

At last but not least, can you also share your k8s manifests, including the `minio` sidecar setup ?

Thanks again for sharing the knowledge, I hope I can move my own nextcloud instance to a similar setup soon (yeah, backup and maintenance are slow and painful in a VM)!

Best Regards!

**Comment by alexblackie** [comment]
>How are you dealing with Nextcloud database?

I run my own PostgreSQL server on Kubernetes as well. It's nice from a cost perspective, as I can share infrastructure with other stuff, and I can more fully control backups which is a downside of most of the hosted postgres options. Specifically, I wanted to use `pg_basebackup` to take full, "bootable" backups of the postgres data directory, and that's only really an option if you run it yourself.

> what is the "final" architecture here?

I "de-Amazoned" myself a few months ago, and moved most stuff to Azure. It's all basically the same, just with AKS for Kubernetes and Azure Storage Blob Containers instead of S3 buckets.

> can you also share your k8s manifests

There's a bit too much semi-private stuff in there to open-source, but [I put the minio manifest in a gist](https://gist.github.com/alexblackie/d052d874fa3c08fd19856d72d2b51093) -- it's all a pretty boring Kubernetes config; just an ingress, service, deployment, and a secret.

The only real trick is using:
```yaml
      containers:
      - name: nxc
        volumeMounts:
        - name: www
          mountPath: /srv/www
      volumes:
      - name: www
        emptyDir: {}
```

on the pod to map the webroot to a temp dir (so `prison` can copy the webroot in there on startup).

Sorry for the delayed response!
